### ISSUE TITLE
UUID foreign key constraint confusion on Ubuntu (only)

### ISSUE THREAD

**Issue by grundoon** [vapor/postgresql#118]
Three models, all `PostgreSQLUUIDModel`, migrated in proper order:
```swift
migrations.add(model: User.self, database: .psql)
migrations.add(model: UserProfile.self, database: .psql)
migrations.add(model: UserNote.self, database: .psql)
```
with `UserNote` `migration`:
```swift
extension UserNote: Migration {
    static func prepare(on connection: PostgreSQLConnection) -> Future<Void> {
        return Database.create(self, on: connection) {
            builder in
            try addProperties(to: builder)
            builder.reference(from: \.userID, to: \User.id)             // foreign key constraint to User
            builder.reference(from: \.profileID, to: \UserProfile.id)   // foreign key constraint to UserProfile
        }
    }
}
```
runs all tests fine on macOS, using standard hub.docker.com `postgres` image.
Attempting to run same on Ubuntu 16.04 (via `swift:4.2`)
```
FROM swift:latest
WORKDIR /package
COPY . .
RUN swift package resolve
RUN swift package clean
CMD ["swift", "test"]
```
however, fails on creating the second foreign key constraint.
```
api_1  | [ INFO ] Preparing migration 'UserNote' (/package/.build/checkouts/fluent.git-7262167429986524690/Sources/Fluent/Migration/Migrations.swift:111)
db_1   | 2019-01-21 21:22:00.027 UTC [32] ERROR:  foreign key constraint "fk:UserNote.profileID+UserProfile.id" cannot be implemented
db_1   | 2019-01-21 21:22:00.027 UTC [32] DETAIL:  Key columns "profileID" and "id" are of incompatible types: uuid and bigint.
db_1   | 2019-01-21 21:22:00.027 UTC [32] STATEMENT:  CREATE TABLE "UserNote" ("id" UUID NOT NULL CONSTRAINT "pk:UserNote.id" PRIMARY KEY, "userID" UUID NOT NULL, "profileID" UUID NOT NULL, "note" TEXT NOT NULL, "createdAt" TIMESTAMP , "updatedAt" TIMESTAMP , "deletedAt" TIMESTAMP , CONSTRAINT "fk:UserNote.userID+User.id" FOREIGN KEY ("userID") REFERENCES "User" ("id"), CONSTRAINT "fk:UserNote.profileID+UserProfile.id" FOREIGN KEY ("profileID") REFERENCES "UserProfile" ("id"))
api_1  | Fatal error: 'try!' expression unexpectedly raised an error: ⚠️ PostgreSQL Error: foreign key constraint "fk:UserNote.profileID+UserProfile.id" cannot be implemented
api_1  | - id: PostgreSQLError.server.error.ATAddForeignKeyConstraint
api_1  |
api_1  | Here are some possible causes:
api_1  | - Key columns "profileID" and "id" are of incompatible types: uuid and bigint.
```
Again, runs fine on macOS (packages, OS and toolchain all release-current) and I guarantee all `ID`s involved are `UUID`s (references are from `UUID` -> `UUID?`).

No issues at all if the 2nd constraint is removed.

**Comment by tanner0101** [comment]
Hmm maybe Postgres is not liking the fact that it's from a `NOT NULL` field to a nullable field? What version of Postgres is running on your server?

**Comment by grundoon** [comment]
Just standard official `postgres` (`postgres:latest` I assume) image:
```
drang:~ grundev$ docker exec -it swiftarr-test bash
root@3f6b4106a44b:/# psql --version
psql (PostgreSQL) 11.1 (Debian 11.1-1.pgdg90+1)
```
And a `NOT NULL` to a nullable is exactly what a `Pivot` does, no? Works fine there.
```
[psql] [2019-01-29 17:31:44 +0000] CREATE TABLE "LikesPivot" ("id" UUID NOT NULL CONSTRAINT "pk:LikesPivot.id" PRIMARY KEY, "userID" UUID NOT NULL, "twarrtID" BIGINT NOT NULL, CONSTRAINT "fk:LikesPivot.userID+User.id" FOREIGN KEY ("userID") REFERENCES "User" ("id") ON DELETE CASCADE, CONSTRAINT "fk:LikesPivot.twarrtID+Twarrt.id" FOREIGN KEY ("twarrtID") REFERENCES "Twarrt" ("id") ON DELETE CASCADE) []
```
But the truly odd part is *only on Linux*.

**Comment by tanner0101** [comment]
@grundoon that is really strange. So you're running 11.1-1 on macOS at least. What about on Linux? Is that running a docker container as well or a local installation?

**Comment by grundoon** [comment]
Well, macOS version is (currently) 9.4.15, but I don't think I've *ever* used that at all – just whatever the official image is for Docker. When I say "Linux", I entirely mean docker containers, so in this case the Ubuntu 16.04 of the official `swift:latest` image. 

I expect the same would be for just about anybody who's gone through the RW book as well (IIRC, twostraws' book uses a local MySQL install... so, I guess perhaps not everybody who's gone a book route has ended up in Docker-land, but majority?).

**Comment by grundoon** [comment]
(after days of this being the case, can. no longer reproduce –  yay? – so am closing for now to stop wasting @tanner0101's time)
