### ISSUE TITLE
Endianness Issues with Postgres "Point" Type

### ISSUE THREAD

**Issue by ericchapman** [vapor/postgresql#125]
Hello,

I appear to be having issues with the endianness when using the ```PostgreSQLPoint``` object in v 1.2.2.  I have a database table with the following schema.  Note that this was created using Rails.

```
my_database-# \d+ my_table;
                                                                  Table "public.my_table"
         Column         |            Type             | Collation | Nullable |                Default               | Storage  | Stats target | Description 
------------------------+-----------------------------+-----------+----------+--------------------------------------+----------+--------------+-------------
 id                     | bigint                      |           | not null | nextval('my_table_id_seq'::regclass) | plain    |              | 
 name                   | character varying           |           |          |                                      | extended |              | 
 coords                 | point                       |           |          |                                      | plain    |              | 
 enabled                | boolean                     |           | not null | true                                 | plain    |              | 
 created_at             | timestamp without time zone |           | not null |                                      | plain    |              | 
 updated_at             | timestamp without time zone |           | not null |                                      | plain    |              | 
```

I created an entry in the table and then queried for it in "psql"

```
my_database=# select * from my_table;
 id |   name     |  coords   | enabled |         created_at         |         updated_at         
----+------------+-----------+---------+----------------------------+----------------------------
  9 |  SOME NAME | (150,100) |    t    | 2019-02-22 14:20:59.529845 | 2019-02-22 14:20:59.529845
(1 row)
```
Note that the "coords" value is "(150,100)" as expected.

I then created the following PostgreSQLModel

``` swift
final class MyTable: PostgreSQLModel {
    static let entity = "my_table"
    
    var id: Int?
    var updated_at: Date?
    var created_at: Date?
    var name: String?
    var coords: PostgreSQLPoint?
    var enabled: Bool?
}
``` 

And run the following query in a Vapor command

``` swift
let myTableObject = try MyTable.query(on: conn).first().wait()
context.console.print("'\(myTableObject?.id ?? 0)'")
context.console.print("'\(myTableObject?.created_at?.description ?? "N/A")'")
context.console.print("'\(myTableObject?.updated_at?.description ?? "N/A")'")
context.console.print("'\(myTableObject?.name ?? "N/A")'")
context.console.print("'\(myTableObject?.coords?.description ?? "N/A")'")
context.console.print("'\(myTableObject?.enabled ?? false)'")
```
and get the following in the Xcode console

```
'9'
'2019-02-22 14:20:59 +0000'
'2019-02-22 14:20:59 +0000'
'SOME NAME'
'(6.2292113e-317,1.12884e-319)'
'true'
```
Note that my coordinates are all messed up.  If I hack the ```PostgreSQLPoint: PostgreSQLDataConvertible``` locally and do the following

``` swift
    ...
    case .binary(let value):
            //let x = value[0..<8]
            //let y = value[8..<16]
            let x = Data(bytes: value[0..<8].reversed())
            let y = Data(bytes: value[8..<16].reversed())
            return .init(x: x.as(Double.self, default: 0), y: y.as(Double.self, default: 0))
    ...
```

When I run this, I get the expected values printed to the screen

```
'9'
'2019-02-22 14:20:59 +0000'
'2019-02-22 14:20:59 +0000'
'SOME NAME'
'(150.0,100.0)'
'true'
```

Is this a simple bug and my local fix is the answer or do different PostgreSQL databases have different endianess and I am running on one that is different than the code this was originally written/tested on?

Would be helpful to know if this code was working when viewing values in "psql" before or if the code is considered "untested".

**Comment by ericchapman** [comment]
Quick update.  I tested this with a normal "Double" attribute for sanity.  This appears to be working as intended where the value is showing up properly in "psql".

It's almost as if the particular "Point" type is storing the values differently than the standard code.  Note that I originally found this while implementing the "Polygon" type where I was seeing a similar behavior.  I am wondering if all of the geometric types are behaving in this fashion.

Note you'll get a PR for the "polygon" one as soon as we figure out the correct resolution for this one.

**Comment by tanner0101** [comment]
Thanks for reporting this. `PostgreSQLPoint` was being tested, but only by encoding / decoding using the same logic. So even though the value was being saved incorrectly in the DB, it was not showing up in tests. I've fixed this issue and added a new test that creates a point in psql from a string to verify we are decoding correctly. See #126.

**Comment by ericchapman** [comment]
Thanks @tanner0101.  I also implemented "Polygon".  Want me to submit a PR and we'll go from there?

**Comment by tanner0101** [comment]
@ericchapman yeah definitely :)
