### ISSUE TITLE
v9 support

### ISSUE THREAD

**Issue by SandorDobi** [vapor/postgresql#13]
Hi,

Supporting the v9 versions (v9.3.x - v9.6.x) is a must if we want to use database as a service from AWS Aurora PostgreSQL or Amazon RDS service or Google Cloud SQL

the vapor server apps are prime candidate  for microservices based server instances deployed into docker farms in AWS or Google or Google App Engine instances
To fully integrate them with cloud provider, they must be able to use database as a service mainly AWS Aurora (MySQL, PostgreSQL) Amazon RDS (MySQL, PostgreSQL) Google Cloud SQL (MySQL PostgreSQL)
Those cloud vendors supporting the v9 PostgreSQL db instances, mainly the last v9 version the v9.6.6.

The v10 version is not so broadly used yet. So to cover the majority of use cases vapor needs to support PostgreSQL v9 preferably v9.6.6

Regards

Sandor Dobi

**Comment by tanner0101** [comment]
I think this is actually just a vapor/fluent-postgresql issue since (iirc) it was complaining about the auto generated ID type. @SandorDobi can you please confirm that's the error you were getting?

If so, that should be an easy enough fix. The difficulty is figuring out which version of PostgreSQL you intend to connect to. This will probably end up being a configuration option on the FluentPostgreSQL provider (either specifically to disable the new "generated" ID syntax, or to specify version more broadly)

**Comment by tanner0101** [comment]
See the relevant code here: https://github.com/vapor/fluent-postgresql/blob/beta/Sources/FluentPostgreSQL/PostgreSQLDatabase%2BSchemaSupporting.swift#L21

**Comment by SandorDobi** [comment]
Yes,

The correct error and the databaselog is the following:
```
Migrating psql DB
[psql] [2018-02-15 20:32:36 +0000] SELECT count(*) as "fluentAggregate" FROM "fluent" []
[psql] [2018-02-15 20:32:36 +0000] CREATE TABLE "fluent" ("id" UUID PRIMARY KEY, "name" TEXT NOT NULL, "batch" BIGINT NOT NULL, "createdAt" TIMESTAMP, "updatedAt" TIMESTAMP) []
[psql] [2018-02-15 20:32:36 +0000] SELECT "fluent".* FROM "fluent" ORDER BY "fluent"."batch" DESC LIMIT 1 OFFSET 0 []
[psql] [2018-02-15 20:32:36 +0000] SELECT "fluent".* FROM "fluent" WHERE ("fluent"."name" = $1) LIMIT 1 OFFSET 0 ["4 bytes"]
[psql] [2018-02-15 20:32:36 +0000] CREATE TABLE "todos" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "title" TEXT NOT NULL) []
crash... ⚠️ [PostgreSQL.PostgreSQLDiagnosticResponse.scanner_yyerror: ERROR: syntax error at or near "GENERATED"] [Possible causes: syntax error at or near "GENERATED"]
```
It is a new vapor beta app where todo model was changed to PostgreSQL from SQLite, otherways it is unchanged.

The used database server: v9.6.1.0
I think for start it would be very good if we can support the v9.6.x.x,  this is the latest of the v9 series and it is very popular.

**Comment by tanner0101** [comment]
Sounds good. Closing in favor of https://github.com/vapor/fluent-postgresql/issues/6
