### ISSUE TITLE
Index out of bounds array crash

### ISSUE THREAD

**Issue by 0xTim** [vapor/postgresql#24]
https://github.com/vapor/postgresql/blob/master/Sources/PostgreSQL/Message/PostgreSQLRowDescription.swift#L34

Hitting an issue here when trying to set up a relationship between two models. I have one model that looks like:

```swift
final class Acronym: Codable {
  var id: Int?
  var short: String
  var long: String
  var userID: User.ID

  init(short: String, long: String, userID: User.ID) {
    self.short = short
    self.long = long
    self.userID = userID
  }
}
```

And a category that looks like:
```swift
final class Category: Codable {
  var id: Int?
  var name: String

  init(name: String) {
    self.name = name
  }
}
```

The route handler looks like:

```swift
  func addCategoriesHandler(_ req: Request) throws -> Future<HTTPStatus> {
    return try flatMap(to: HTTPStatus.self, req.parameter(Acronym.self), req.parameter(Category.self)) { acronym, category in
      let pivot = try AcronymCategoryPivot(acronym.requireID(), category.requireID())
      return pivot.save(on: req).transform(to: .created)
    }
  }
```

The crash happens when unwrapping this futute `return try flatMap(to: HTTPStatus.self, req.parameter(Acronym.self), req.parameter(Category.self)) { acronym, category in`

**Comment by tanner0101** [comment]
@0xTim any way you could enable query logging (using the migration config struct) and show me which query is causing this?

**Comment by 0xTim** [comment]
@tanner0101 query is 
```
[psql] [2018-03-14 20:11:50 +0000] SELECT "categories".* FROM "categories" WHERE ("categories"."id" = $1) LIMIT 1 OFFSET 0 ["8 bytes"]
```
So it's obviously got some cache of the acronyms data on the event loop or something like that
