### ISSUE TITLE
Migrating psql DB fails when using Decimal type on models 

### ISSUE THREAD

**Issue by NZTimKeegan** [vapor/postgresql#37]
### Expected Behavior
Database should be created including column for Decimal property

### Actual Behavior
```Thread 1: Fatal error``` points to line 179 of the file Decodable+CodingPath.swift (path: Core 3.0.0-rc.1.0.1/CodableKit/Key)

With logging enabled:
```swift
databaseConfig.enableLogging(on: .psql)
```

the output is: 
```sql
Migrating psql DB
[psql] [2018-03-20 20:39:24 +0000] SELECT count(*) as "fluentAggregate" FROM "fluent" []
[psql] [2018-03-20 20:39:24 +0000] SELECT "fluent".* FROM "fluent" ORDER BY "fluent"."batch" DESC LIMIT 1 OFFSET 0 []
[psql] [2018-03-20 20:39:24 +0000] SELECT "fluent".* FROM "fluent" WHERE ("fluent"."name" = $1) LIMIT 1 OFFSET 0 ["7 bytes"]
[psql] [2018-03-20 20:39:24 +0000] SELECT "fluent".* FROM "fluent" WHERE ("fluent"."name" = $1) LIMIT 1 OFFSET 0 ["6 bytes"]
[psql] [2018-03-20 20:39:24 +0000] SELECT "fluent".* FROM "fluent" WHERE ("fluent"."name" = $1) LIMIT 1 OFFSET 0 ["18 bytes"]
[psql] [2018-03-20 20:39:24 +0000] SELECT "fluent".* FROM "fluent" WHERE ("fluent"."name" = $1) LIMIT 1 OFFSET 0 ["13 bytes"]
```

### Steps to Reproduce the Problem

  1. Create new project (e.g. vapor new api-template --template=api --branch=beta )
  1. Add Postgres config 
  1. Add decimal property to model

  ```swift
  import FluentPostgreSQL
  import Foundation
  import Vapor

  struct Todo: Content, Migration, Parameter, PostgreSQLModel {
    var id: Int?
    var decimal: Decimal
  }
  ```
  
  1. Hit Run
![screen shot 2018-03-21 at 09 51 06](https://user-images.githubusercontent.com/31173595/37682307-1b7c51f8-2cee-11e8-8da4-ce0a4984bda8.png)

### Specifications

  - Versions: 
    - Vapor Toolbox 3.1.4
    - Swift 4.1
    - Xcode 9.3 beta 4

**Comment by tanner0101** [comment]
`Decimal` encodes to JSON, like:

```
{"exponent":-3,"length":1,"isCompact":true,"isNegative":true,"mantissa":[1234,0,0,0,0,0,0,0]} (JSONB)
```

This is desired since it allows the type to store values with higher precision than Float and Double. I've added a test to make sure this is working in the latest build, just make sure to use a `JSONB` column type 👍 .
