### ISSUE TITLE
Using this library without Vapor/CLI?

### ISSUE THREAD

**Issue by stephencelis** [vapor/postgresql#42]
This library appears to depend on the Vapor CLI to generate Xcode projects that are module-mapped, libressl-compatible. Are there instructions on how to integrate it with non-Vapor apps?

**Comment by 0xTim** [comment]
@stephencelis you should be able to build a non-Vapor app with SPM by just adding the library as a dependency. For non-SPM you may be out of luck - is that what you are trying to do?

**Comment by stephencelis** [comment]
I'm using SPM. This library appears to depend on generating an Xcode project via `vapor` in order to set up libressl module maps.

**Comment by vzsg** [comment]
That assumption is simply incorrect - it's SPM building the module maps by itself, the vapor toolbox simply invokes `swift package generate-xcodeproj`.

Note that you _do_ need to have `libressl` installed via Homebrew. Pretty much all packages of the Vapor 3 ecosystem depend on it on macOS.
