### ISSUE TITLE
Bad date calculations

### ISSUE THREAD

**Issue by grosch** [vapor/postgresql#53]
https://github.com/vapor/postgresql/blob/388346471c6a89c2695235d8ffff43c5941283af/Sources/PostgreSQL/Data/PostgreSQLData%2BDate.swift#L32

You're doing date calculations by using seconds, which is always a bad thing to begin with.  

However, I'm hitting a case where the app crashes with 

> NIO-ELT-#1 (4): EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

I believe it's because the days is coming through as a negative number.

**Comment by grosch** [comment]
I just found this `date` value in my database

> 0214-02-05

I'm sure that's what's making it die.  Obviously that's corrupt data in my database that I need to fix.

**Comment by MrMage** [comment]
If it crashes Vapor, we should probably look into fixing it anyway. Do you have a reproducible case?

Also, why is using seconds for date calculations bad?

**Comment by grosch** [comment]
https://developer.apple.com/videos/play/wwdc2011/117/ talks all about why it's bad.  But at the end of the day, no pun intended, there aren't always 24 * 60 * 60 seconds in a day.

I think it's reproducible by just setting the date to what I showed above.

**Comment by MrMage** [comment]
That's a different use case. For timestamps, "number of seconds since some reference date" is the standard way of doing things as far as I know. IIRC this is actually how Postgres stores timestamps internally.

**Comment by tanner0101** [comment]
The issue was integer overflow. Fixed by using `Int64`.
