### ISSUE TITLE
Can not convert a UInt8 enum or Int64 back

### ISSUE THREAD

**Issue by anthonycastelli** [vapor/postgresql#61]
When trying to convert the data in Postgres back to a UInt8 enum fails with the error 
```
[ ERROR ] DecodingError.typeMismatch: Value of type 'UInt8' required for key ''. (EngineServer.swift:157)
```

My enum extension is 
```swift
extension RawRepresentable where RawValue == UInt8, Self: PostgreSQLColumnStaticRepresentable, Self: PostgreSQLDataConvertible {
    static var postgreSQLColumn: PostgreSQLColumn {
        return RawValue.postgreSQLColumn
    }
}
```

Saving data to the database works fine, just retrieving it fails. 
When defining an`Int64` in a model, the same thing occurs. 
```
[ ERROR ] DecodingError.typeMismatch: Value of type 'Int64' required for key ''. (EngineServer.swift:157)
```

**Comment by anthonycastelli** [comment]
After looking into this a bit more, it appears and int of `30` gets saved as a float8 to `bpchar(1)` in the table. Then when it's converted back, the data type is `DOUBLE PRECISION - raw : 701`

```
(lldb) po data.format
PostgreSQL.PostgreSQLFormatCode.binary

(lldb) po data.type
▿ DOUBLE PRECISION
  - raw : 701
```

**Comment by tanner0101** [comment]
@anthonycastelli a small repro case would be helpful here. I'm very confused as to way `bpchar` or `DOUBLE PRECISION` would be involved when using `UInt8`.

**Comment by anthonycastelli** [comment]
@tanner0101 I'll get a sample project put together tonight/tomorrow for this 👍

**Comment by anthonycastelli** [comment]
@tanner0101 Here is a project to reproduce this issue. I also added the `or` query from #64 


[Bug61.zip](https://github.com/vapor/postgresql/files/2065207/Bug61.zip)

**Comment by tanner0101** [comment]
Closing this in favor of https://github.com/vapor/fluent-postgresql/issues since that is the repo affected. A link to this issue will appear there. Thanks!
