### ISSUE TITLE
Use `nil` as a value in a parameterized query

### ISSUE THREAD

**Issue by addisonwebb** [vapor/postgresql#65]
I’m still a little fuzzy on how a parameter is turned into data that is stored into the database but I don’t think it is possible to do this currently.

This is an example of what I am trying to do.

Schema:
``` sql
CREATE TABLE media_types (
    id uuid NOT NULL PRIMARY KEY,
    parent uuid
);
```

Query:
``` swift
class Item {
	let id: UUID
	let parent: UUID?

	init(_ id: UUID, parent: UUID?) {
		...
	}
}

let item = Item(UUID(), parent: nil)

connection.query("INSERT INTO test_table (id, parent) VALUES ($1, $2) ON CONFLICT (id) DO NOTHING;", [item.id, item.parent]).wait()
```

I would expect that query to be equivalent to this SQL statement (which I verified works as expected):

``` sql
INSERT INTO item_table (id, parent) VALUES ('BA4A2E9D-CCC2-433B-9D2B-E94A5F686122', NULL) ON CONFLICT (id) DO NOTHING;
```

The problem is when I run this I get the following error:
```
Whoops! An error occurred: ⚠️ [PostgreSQLDiagnosticResponse.transformAssignedExpr: ERROR: column "parent" is of type uuid but expression is of type void] [Possible causes: column "parent" is of type uuid but expression is of type void] [Suggested fixes: You will need to rewrite or cast the expression.]
```

From what I can tell the optional `PostgreSQLDataConvertible` into a `PostgreSQLData` object of type `.void` [here](https://github.com/vapor/postgresql/blob/4988607c3b2369248c6cfcd34274241a8632cd69/Sources/PostgreSQL/Data/PostgreSQLData%2BOptional.swift#L16).  It seems like the framework is trying to match the types of the parameters to the column before attempting the query (I don’t know where this is happening though). If this is the case it would makes sense why I am getting the error. 

I think it is desirable to be able to use `nil` as a parameter so I don’t have to manually construct the query being careful to only add items that have non-nil values.

I would be willing to help address this issue if someone could point me in the right direction. (Or show me how the framework already allows me to do this 😆)

**Comment by addisonwebb** [comment]
It doesn't seem like this is an issue across the entire framework. From my testing it might only be an issue with how certain types are handled.

**Comment by tanner0101** [comment]
@addisonwebb this issue has been tackled in #72. Previously this library would use a `.void` data type if it could not resolve type information (such as in the case of nil). That has been changed to using `.null` which fixes the `rewrite or cast the expression` error.

That being said, SQL is still pretty finicky about null values. And the different database implements all have their own quirks. When in doubt, use `NULL` literal in the query string. vapor/sql has a special type for doing that.

**Comment by addisonwebb** [comment]
👍 awesome! Thanks @tanner0101 !
