### ISSUE TITLE
Unable to decode from Timestampable column as expecting Double

### ISSUE THREAD

**Issue by jonny7** [vapor/postgresql#67]
I've just started testing some simple routes and come across the following failure. This route doesn't fail in normal circumstances, it returns as expected in Postman etc.

But for testing I am getting the following error:
> ⚠️ [DecodingError.typeMismatch: Value of type 'Double' required for key 'createdAt'.]

The structure of my model is:

```
    var id: UUID?
     ...
    var createdAt: Date?
    var updatedAt: Date?
```

Both the `createdAt` and `updatedAt` were created by fluent using the `Timestampable` protocol. 
The response that is coming back is:
```
...
"updatedAt":"2018-05-16T23:45:34Z",
"createdAt":"2018-05-16T23:45:34Z",
...
```
I am seeing in PGAdmin4 that the column is represented in the format `2018-05-19 00:00:29.903729`

This is the function I was using to get the response
```swift
func getResponse<T>(to path: String, method: HTTPMethod = .GET, headers: HTTPHeaders = .init(), body: HTTPBody = .init(), decodeTo type: T.Type) throws
        -> T where T: Decodable {
            // use the first method to get the response
            let response = try self.sendRequest(to: path, method: method, headers: headers, body: body)
            // decode to a generic type and return the response
            //return try JSONDecoder().decode(type, from: response.http.body.data!)
            do {
                try JSONDecoder().decode(type, from: response.http.body.data!)
            } catch let e{
                print(e)
            }
            return try JSONDecoder().decode(type, from: response.http.body.data!)
    }
```

I caught the error to check the actual response which seemed as I would have expected.

**Comment by MrMage** [comment]
`JSONEncoder` by default encodes dates as double-valued Unix timestamp (see e.g. [here](https://benscheirman.com/2017/06/swift-json/)). Is it possible that your own JSON de-/encoding is failing? In that case, this would have nothing to do with PostgreSQL.

**Comment by vzsg** [comment]
If only JSONEncoder defaulted to Unix timestamps! The default is actually using the Apple-specific "number of seconds since reference date (2011-01-01)".

**Comment by MrMage** [comment]
Ouch, you are right; sorry about the incorrect statement. Reference date is really a bad default.

**Comment by tanner0101** [comment]
I'm not 100% clear on what the error is here. There are tests in vapor/postgresql testing that `Date` goes to/from the db layer without losing precision so I would be surprised if it's a problem here.

If you could provide a stack trace for the following error that would help a lot!
```
⚠️ [DecodingError.typeMismatch: Value of type 'Double' required for key 'createdAt'.]
```

**Comment by jonny7** [comment]
Hi @tanner0101 

Try this simple [repo](https://bitbucket.org/Jonny7/tanner/src/master/) I made. It has exhibited the same problem as my problem project. Let me know if there's any problem with the repo. I'm using the testing set up from the book. 😄

**Comment by tanner0101** [comment]
@jonny7 can you run `swift package update` and try again? There has been a lot of cleanup in the decoder and new unit tests added. I would be surprised if this issue continues to happen now. Thanks!
