### ISSUE TITLE
Using custom types in columns

### ISSUE THREAD

**Issue by broadwaylamb** [vapor/postgresql#69]
I have a custom enum type that I want to map to a PostgreSQL enum:

```swift
enum MyEnum: String, Codable {
    case a, b, c
}

extension MyEnum: PostgreSQLEnumType {
    // Implemenation of the conformance
}
```

I also have an entity which I want to have a column of type `MyEnum`. I understand that I need to create a custom migration for that, and that's what I do now:

```swift
extension MyEntity: Migration {
    
    public static func prepare(
        on connection: Database.Connection
    ) -> Future<Void> {

        let query = """
        CREATE TYPE "\(MyEnum.self)" AS ENUM ('a', 'b', 'c');
        """

        return connection.simpleQuery(query)
            .flatMap(to: Void.self) { _ in
                Database.create(self, on: connection) { builder in
                    try addProperties(to: builder)
                }
            }.flatMap(to: Void.self) {

                let enumColumnName = try (\MyEntity.enumColumn).makeQueryField().name

                let alterColumnType = """
                ALTER TABLE "\(entity)"
                    ALTER COLUMN "\(enumColumnName)" TYPE "\(MyEnum.self)"
                    USING "\(enumColumnName)"::"\(MyEnum.self)";
                """

                return connection.simpleQuery(alterColumnType).transform(to: ())
            }
    }
}
```

It would be great if we could do without custom SQL queries, at least when building a schema, something like this:

```swift
Database.create(self, on: connection) { builder in
    // ...
    builder.field(type: PostgreSQLColumn(customTypeName: "\(MyEnum.self)"),
                  for: \MyEntity.enumColumn)
}
```

I can create a PR if I'm not the only one who thinks this is a nice addition :)

**Comment by tanner0101** [comment]
This should be much easier to do now with the updates in #72. That will give you access to the underlying vapor/sql types used to serialize the SQL query. They will allow you to pass a custom string through as the type name. 

You might also be able to do this by conforming `MyEnum` to `PostgreSQLType` and not have to implement a custom migration 👍 

Keep your eyes on #72 to get merged. Closing this.
