### ISSUE TITLE
Cannot build 1.0.0-rc.4.1

### ISSUE THREAD

**Issue by kliron** [vapor/postgresql#83]
Here is my dependencies in `Package.swift`:

```
dependencies: [
        .package(url: "https://github.com/vapor/vapor.git", from: "3.0.0"),
        .package(url: "https://github.com/vapor/postgresql.git", from: "1.0.0-rc"),
    ],
```

I could compile my project just fine until `1.0.0-rc.4`. After updating to `rc.4.1` I get compile errors:

In `PostgreSQLQuery` enum:
 
`Type 'PostgreSQLQuery' does not conform to protocol 'SQLQuery'` And Xcode suggests fixing by adding `public typealias CreateTable = <type>`  stub even though this typealias exists from what I can see. 

And in `serialize`method of same enum:

In `.createTable(let createTable)` case: ` Pattern cannot match values of type 'PostgreSQLQuery'`

In `PostgreSQLGeneric`:

at `public typealias PostgreSQLForeignKeyAction = GenericSQLForeignKeyAction` I get `Use of undeclared type 'GenericSQLForeignKeyAction' `

In `PostgreSQLAlterTable` struct:

`Type 'PostgreSQLAlterTable' does not conform to protocol 'SQLAlterTable'`

And in `serialize` method of this struct: `Escaping closures can only capture inout parameters explicitly by value`

In `PostgreSQLGeneric.swift` file:

at `public typealias PostgreSQLForeignKeyAction = GenericSQLForeignKeyAction` I get  `Use of undeclared type 'GenericSQLForeignKeyAction'`

**Comment by tanner0101** [comment]
Try running `swift package update` again. You likely pulled at an unlucky time while packages were being tagged. 

Also try `rm -rf .build; rm -rf Package.resolved` if you are still having problems.

(We can re-open if that for some reason doesn't fix it)

**Comment by kliron** [comment]
Thanks. 
Strange. I did `rm -rf .build; rm -rf Package.resolved; swift package update` more than one time before posting here, but today it worked fine.
