### ISSUE TITLE
How to extension PostgreSQLTableIdentifier

### ISSUE THREAD

**Issue by vkill** [vapor/postgresql#87]
In this [PR](https://github.com/vapor/sql/pull/12), to extension PostgreSQLTableIdentifier is a good plan, but hot to extension it?

This is wrong style.
```
extension GenericSQLTableIdentifier {
    public func serialize(_ binds: inout [Encodable]) -> String {
        if self.identifier.string == "EXCLUDED" {
            return "EXCLUDED"
        }
        return identifier.serialize(&binds)
    }
}
public typealias PostgreSQLTableIdentifier = GenericSQLTableIdentifier<PostgreSQLIdentifier>
```

**Comment by tanner0101** [comment]
@vkill you'll want to create a custom struct that conforms to `SQLTableIdentifier`. You can take a look at `PostgreSQLIdentifier` to see an example of how it's done.
